// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package Base

import "fyne.io/fyne/v2"

var resourceAimingSvg = &fyne.StaticResource{
	StaticName: "aiming.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"24\" r=\"20\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24 37V44V37Z\" fill=\"none\"/><path d=\"M24 37V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M36 24H44H36Z\" fill=\"none\"/><path d=\"M36 24H44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M4 24H11H4Z\" fill=\"none\"/><path d=\"M4 24H11\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24 11V4V11Z\" fill=\"none\"/><path d=\"M24 11V4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceAllApplicationSvg = &fyne.StaticResource{
	StaticName: "all-application.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M18 6H8C6.89543 6 6 6.89543 6 8V18C6 19.1046 6.89543 20 8 20H18C19.1046 20 20 19.1046 20 18V8C20 6.89543 19.1046 6 18 6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M18 28H8C6.89543 28 6 28.8954 6 30V40C6 41.1046 6.89543 42 8 42H18C19.1046 42 20 41.1046 20 40V30C20 28.8954 19.1046 28 18 28Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M40 6H30C28.8954 6 28 6.89543 28 8V18C28 19.1046 28.8954 20 30 20H40C41.1046 20 42 19.1046 42 18V8C42 6.89543 41.1046 6 40 6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M40 28H30C28.8954 28 28 28.8954 28 30V40C28 41.1046 28.8954 42 30 42H40C41.1046 42 42 41.1046 42 40V30C42 28.8954 41.1046 28 40 28Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBillSvg = &fyne.StaticResource{
	StaticName: "bill.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10 6C10 4.89543 10.8954 4 12 4H36C37.1046 4 38 4.89543 38 6V44L31 39L24 44L17 39L10 44V6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 22L30 22\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 30L30 30\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 14L30 14\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBookmarkOneSvg = &fyne.StaticResource{
	StaticName: "bookmark-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M34 10V4H8V38L14 35\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M14 44V10H40V44L27 37.7273L14 44Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBookmarkSvg = &fyne.StaticResource{
	StaticName: "bookmark.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10 44C8.89543 44 8 43.1046 8 42V6C8 4.89543 8.89543 4 10 4H38C39.1046 4 40 4.89543 40 6V42C40 43.1046 39.1046 44 38 44H10Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M21 22V4H33V22L27 15.7273L21 22Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 4H38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceCameraSvg = &fyne.StaticResource{
	StaticName: "camera.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M15 12L18 6H30L33 12H15Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><rect x=\"4\" y=\"12\" width=\"40\" height=\"30\" rx=\"3\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 35C28.4183 35 32 31.4183 32 27C32 22.5817 28.4183 19 24 19C19.5817 19 16 22.5817 16 27C16 31.4183 19.5817 35 24 35Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceConfigSvg = &fyne.StaticResource{
	StaticName: "config.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 4L18 10H10V18L4 24L10 30V38H18L24 44L30 38H38V30L44 24L38 18V10H30L24 4Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 30C27.3137 30 30 27.3137 30 24C30 20.6863 27.3137 18 24 18C20.6863 18 18 20.6863 18 24C18 27.3137 20.6863 30 24 30Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceDeleteTwoSvg = &fyne.StaticResource{
	StaticName: "delete-two.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M14 11L4 24L14 37H44V11H14Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M21 19L31 29\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 19L21 29\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceDislikeTwoSvg = &fyne.StaticResource{
	StaticName: "dislike-two.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M15 8C8.92487 8 4 12.9249 4 19C4 30 17 40 24 42.3262C31 40 44 30 44 19C44 12.9249 39.0751 8 33 8C29.2797 8 25.9907 9.8469 24 12.6738C22.0093 9.8469 18.7203 8 15 8Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M28 20L20 28L28 20Z\" fill=\"none\"/><path d=\"M28 20L20 28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M20 20.0001L28 28L20 20.0001Z\" fill=\"none\"/><path d=\"M20 20.0001L28 28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceDislikeSvg = &fyne.StaticResource{
	StaticName: "dislike.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 31L21 26L28 20L19 15L20 9.19942C18.4999 8.43256 16.8004 8 15 8C8.92487 8 4 12.9249 4 19C4 30 17 40 24 42C31 40 44 30 44 19C44 12.9249 39.0751 8 33 8C31.1996 8 29.5001 8.43256 28 9.19942\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceEqualizerSvg = &fyne.StaticResource{
	StaticName: "equalizer.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M11 16V42\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 29V42\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 19V6\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M37 6V32\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M11 16C13.7614 16 16 13.7614 16 11C16 8.23858 13.7614 6 11 6C8.23858 6 6 8.23858 6 11C6 13.7614 8.23858 16 11 16Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 29C26.7614 29 29 26.7614 29 24C29 21.2386 26.7614 19 24 19C21.2386 19 19 21.2386 19 24C19 26.7614 21.2386 29 24 29Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M37 42C39.7614 42 42 39.7614 42 37C42 34.2386 39.7614 32 37 32C34.2386 32 32 34.2386 32 37C32 39.7614 34.2386 42 37 42Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceFemaleSvg = &fyne.StaticResource{
	StaticName: "female.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><g clip-path=\"url(#icon-d1013ebccbbd09)\"><path d=\"M38.3785 9.85132C32.9112 4.38398 24.0468 4.38398 18.5795 9.85132C15.8458 12.585 14.479 16.1679 14.479 19.7508C14.479 23.3337 15.8458 26.9166 18.5795 29.6503C24.0468 35.1176 32.9112 35.1176 38.3785 29.6503C43.8458 24.183 43.8458 15.3187 38.3785 9.85132Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M18.4642 29.5353L5.73633 42.2632\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19.1714 41.5562L6.44346 28.8282\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g><defs><clipPath id=\"icon-d1013ebccbbd09\"><rect width=\"48\" height=\"48\" fill=\"#333\"/></clipPath></defs></svg>"),
}
var resourceHamburgerButtonSvg = &fyne.StaticResource{
	StaticName: "hamburger-button.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7.94971 11.9497H39.9497\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7.94971 23.9497H39.9497\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7.94971 35.9497H39.9497\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceHomeSvg = &fyne.StaticResource{
	StaticName: "home.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M9 18V42H39V18L24 6L9 18Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 29V42H29V29H19Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M9 42H39\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>"),
}
var resourceHourglassFullSvg = &fyne.StaticResource{
	StaticName: "hourglass-full.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 4H41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 44H41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M11 44C13.6667 30.6611 18 23.9944 24 24C30 24.0056 34.3333 30.6722 37 44H11Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M37 4C34.3333 17.3389 30 24.0056 24 24C18 23.9944 13.6667 17.3278 11 4H37Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M21 15H27\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 38H29\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceHourglassNullSvg = &fyne.StaticResource{
	StaticName: "hourglass-null.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 4H41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 44H41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M11 44C13.6667 30.6611 18 23.9944 24 24C30 24.0056 34.3333 30.6722 37 44H11Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M37 4C34.3333 17.3389 30 24.0056 24 24C18 23.9944 13.6667 17.3278 11 4H37Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceLightningSvg = &fyne.StaticResource{
	StaticName: "lightning.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M19 4H37L26 18H41L17 44L22 25H8L19 4Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceLikeSvg = &fyne.StaticResource{
	StaticName: "like.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M15 8C8.92487 8 4 12.9249 4 19C4 30 17 40 24 42.3262C31 40 44 30 44 19C44 12.9249 39.0751 8 33 8C29.2797 8 25.9907 9.8469 24 12.6738C22.0093 9.8469 18.7203 8 15 8Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceLoadingFourSvg = &fyne.StaticResource{
	StaticName: "loading-four.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 24C4 35.0457 12.9543 44 24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceLoadingSvg = &fyne.StaticResource{
	StaticName: "loading.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 24C4 35.0457 12.9543 44 24 44V44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M36 24C36 17.3726 30.6274 12 24 12C17.3726 12 12 17.3726 12 24C12 30.6274 17.3726 36 24 36V36\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceMaleSvg = &fyne.StaticResource{
	StaticName: "male.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M41.9517 15.0483V6.04834H32.9517\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10.4135 38.0007C15.8808 43.4681 24.7451 43.4681 30.2125 38.0007C32.9462 35.2671 34.313 31.6841 34.313 28.1012C34.313 24.5183 32.9462 20.9354 30.2125 18.2017C24.7451 12.7344 15.8808 12.7344 10.4135 18.2017C4.94615 23.6691 4.94615 32.5334 10.4135 38.0007Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M30.0002 17.9999L39.9517 8.04838\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceMoreAppSvg = &fyne.StaticResource{
	StaticName: "more-app.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M18 4H6C4.89543 4 4 4.89543 4 6V18C4 19.1046 4.89543 20 6 20H18C19.1046 20 20 19.1046 20 18V6C20 4.89543 19.1046 4 18 4Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M18 28H6C4.89543 28 4 28.8954 4 30V42C4 43.1046 4.89543 44 6 44H18C19.1046 44 20 43.1046 20 42V30C20 28.8954 19.1046 28 18 28Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M42 4H30C28.8954 4 28 4.89543 28 6V18C28 19.1046 28.8954 20 30 20H42C43.1046 20 44 19.1046 44 18V6C44 4.89543 43.1046 4 42 4Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M28 28H44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M36 36H44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M28 44H44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceMoreOneSvg = &fyne.StaticResource{
	StaticName: "more-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"12\" r=\"3\" fill=\"#333\"/><circle cx=\"24\" cy=\"24\" r=\"3\" fill=\"#333\"/><circle cx=\"24\" cy=\"35\" r=\"3\" fill=\"#333\"/></svg>"),
}
var resourceMoreTwoSvg = &fyne.StaticResource{
	StaticName: "more-two.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><circle cx=\"14\" cy=\"24\" r=\"3\" fill=\"#333\"/><circle cx=\"24\" cy=\"24\" r=\"3\" fill=\"#333\"/><circle cx=\"34\" cy=\"24\" r=\"3\" fill=\"#333\"/></svg>"),
}
var resourceMoreSvg = &fyne.StaticResource{
	StaticName: "more.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"12\" cy=\"24\" r=\"3\" fill=\"#333\"/><circle cx=\"24\" cy=\"24\" r=\"3\" fill=\"#333\"/><circle cx=\"36\" cy=\"24\" r=\"3\" fill=\"#333\"/></svg>"),
}
var resourcePicSvg = &fyne.StaticResource{
	StaticName: "pic.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M5 10C5 8.89543 5.89543 8 7 8L41 8C42.1046 8 43 8.89543 43 10V38C43 39.1046 42.1046 40 41 40H7C5.89543 40 5 39.1046 5 38V10Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M14.5 18C15.3284 18 16 17.3284 16 16.5C16 15.6716 15.3284 15 14.5 15C13.6716 15 13 15.6716 13 16.5C13 17.3284 13.6716 18 14.5 18Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 24L20 28L26 21L43 34V38C43 39.1046 42.1046 40 41 40H7C5.89543 40 5 39.1046 5 38V34L15 24Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourcePowerSvg = &fyne.StaticResource{
	StaticName: "power.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M14.5 8C13.8406 8.37652 13.2062 8.79103 12.6 9.24051C11.5625 10.0097 10.6074 10.8814 9.75 11.8402C6.79377 15.1463 5 19.4891 5 24.2455C5 34.6033 13.5066 43 24 43C34.4934 43 43 34.6033 43 24.2455C43 19.4891 41.2062 15.1463 38.25 11.8402C37.3926 10.8814 36.4375 10.0097 35.4 9.24051C34.7938 8.79103 34.1594 8.37652 33.5 8\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 4V24\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourcePreviewCloseOneSvg = &fyne.StaticResource{
	StaticName: "preview-close-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M9.85786 18C6.23858 21 4 24 4 24C4 24 12.9543 36 24 36C25.3699 36 26.7076 35.8154 28 35.4921M20.0318 12.5C21.3144 12.1816 22.6414 12 24 12C35.0457 12 44 24 44 24C44 24 41.7614 27 38.1421 30\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20.3142 20.6211C19.4981 21.5109 19 22.6972 19 23.9998C19 26.7612 21.2386 28.9998 24 28.9998C25.3627 28.9998 26.5981 28.4546 27.5 27.5705\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M42 42L6 6\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourcePreviewCloseSvg = &fyne.StaticResource{
	StaticName: "preview-close.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 16C6.63472 17.2193 7.59646 18.3504 8.82276 19.3554C12.261 22.1733 17.779 24 24 24C30.221 24 35.739 22.1733 39.1772 19.3554C40.4035 18.3504 41.3653 17.2193 42 16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M28.9775 24L31.048 31.7274\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M37.3535 21.3536L43.0103 27.0104\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5.00004 27.0103L10.6569 21.3534\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16.9278 31.7276L18.9983 24.0001\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourcePreviewOpenSvg = &fyne.StaticResource{
	StaticName: "preview-open.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 36C35.0457 36 44 24 44 24C44 24 35.0457 12 24 12C12.9543 12 4 24 4 24C4 24 12.9543 36 24 36Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 29C26.7614 29 29 26.7614 29 24C29 21.2386 26.7614 19 24 19C21.2386 19 19 21.2386 19 24C19 26.7614 21.2386 29 24 29Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceRadarSvg = &fyne.StaticResource{
	StaticName: "radar.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24 34C29.5228 34 34 29.5228 34 24C34 18.4772 29.5228 14 24 14C18.4772 14 14 18.4772 14 24C14 29.5228 18.4772 34 24 34Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 4V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 24.0002L18 24.0086\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M4 24.0083L44 24.0083\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceRefreshSvg = &fyne.StaticResource{
	StaticName: "refresh.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M42 8V24\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 24L6 40\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M42 24C42 14.0589 33.9411 6 24 6C18.9145 6 14.3216 8.10896 11.0481 11.5M6 24C6 33.9411 14.0589 42 24 42C28.8556 42 33.2622 40.0774 36.5 36.9519\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceRssSvg = &fyne.StaticResource{
	StaticName: "rss.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M8 44L8 6C8 4.89543 8.89543 4 10 4H38C39.1046 4 40 4.89543 40 6V44L24 35.7273L8 44Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M23.9497 13.9497L23.9497 25.9497\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17.9497 19.9497L29.9497 19.9497\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSaveOneSvg = &fyne.StaticResource{
	StaticName: "save-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M39.3 6H8.7C7.20883 6 6 7.20883 6 8.7V39.3C6 40.7912 7.20883 42 8.7 42H39.3C40.7912 42 42 40.7912 42 39.3V8.7C42 7.20883 40.7912 6 39.3 6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M32 6V24H15V6H32Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M26 13V17\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M10.9971 6H35.9986\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>"),
}
var resourceSaveSvg = &fyne.StaticResource{
	StaticName: "save.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6 9C6 7.34315 7.34315 6 9 6H34.2814L42 13.2065V39C42 40.6569 40.6569 42 39 42H9C7.34315 42 6 40.6569 6 39V9Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M24.0083 6L24 13.3846C24 13.7245 23.5523 14 23 14H15C14.4477 14 14 13.7245 14 13.3846L14 6\" fill=\"none\"/><path d=\"M24.0083 6L24 13.3846C24 13.7245 23.5523 14 23 14H15C14.4477 14 14 13.7245 14 13.3846L14 6H24.0083Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M9 6H34.2814\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M14 26H34\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M14 34H24.0083\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSearchSvg = &fyne.StaticResource{
	StaticName: "search.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21 38C30.3888 38 38 30.3888 38 21C38 11.6112 30.3888 4 21 4C11.6112 4 4 11.6112 4 21C4 30.3888 11.6112 38 21 38Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M26.657 14.3431C25.2093 12.8954 23.2093 12 21.0001 12C18.791 12 16.791 12.8954 15.3433 14.3431\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33.2216 33.2217L41.7069 41.707\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSettingConfigSvg = &fyne.StaticResource{
	StaticName: "setting-config.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M41.5 10H35.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27.5 6V14\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27.5 10L5.5 10\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M13.5 24H5.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M21.5 20V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M43.5 24H21.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M41.5 38H35.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27.5 34V42\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27.5 38H5.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSettingOneSvg = &fyne.StaticResource{
	StaticName: "setting-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M34.0003 41L44 24L34.0003 7H14.0002L4 24L14.0002 41H34.0003Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 29C26.7614 29 29 26.7614 29 24C29 21.2386 26.7614 19 24 19C21.2386 19 19 21.2386 19 24C19 26.7614 21.2386 29 24 29Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSettingThreeSvg = &fyne.StaticResource{
	StaticName: "setting-three.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"24\" r=\"15\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 39V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M39 23H44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 23H9\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 4V9\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M34.6064 34.6064L38.142 38.142\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33.8994 12.6865L37.4349 9.15099\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9.15088 37.4351L12.6864 33.8995\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M9.85791 9.85791L13.3934 13.3934\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSettingTwoSvg = &fyne.StaticResource{
	StaticName: "setting-two.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M18.2838 43.1713C14.9327 42.1736 11.9498 40.3213 9.58787 37.867C10.469 36.8227 11 35.4734 11 34.0001C11 30.6864 8.31371 28.0001 5 28.0001C4.79955 28.0001 4.60139 28.01 4.40599 28.0292C4.13979 26.7277 4 25.3803 4 24.0001C4 21.9095 4.32077 19.8938 4.91579 17.9995C4.94381 17.9999 4.97188 18.0001 5 18.0001C8.31371 18.0001 11 15.3138 11 12.0001C11 11.0488 10.7786 10.1493 10.3846 9.35011C12.6975 7.1995 15.5205 5.59002 18.6521 4.72314C19.6444 6.66819 21.6667 8.00013 24 8.00013C26.3333 8.00013 28.3556 6.66819 29.3479 4.72314C32.4795 5.59002 35.3025 7.1995 37.6154 9.35011C37.2214 10.1493 37 11.0488 37 12.0001C37 15.3138 39.6863 18.0001 43 18.0001C43.0281 18.0001 43.0562 17.9999 43.0842 17.9995C43.6792 19.8938 44 21.9095 44 24.0001C44 25.3803 43.8602 26.7277 43.594 28.0292C43.3986 28.01 43.2005 28.0001 43 28.0001C39.6863 28.0001 37 30.6864 37 34.0001C37 35.4734 37.531 36.8227 38.4121 37.867C36.0502 40.3213 33.0673 42.1736 29.7162 43.1713C28.9428 40.752 26.676 39.0001 24 39.0001C21.324 39.0001 19.0572 40.752 18.2838 43.1713Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 31C27.866 31 31 27.866 31 24C31 20.134 27.866 17 24 17C20.134 17 17 20.134 17 24C17 27.866 20.134 31 24 31Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSettingSvg = &fyne.StaticResource{
	StaticName: "setting.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M36.686 15.171C37.9364 16.9643 38.8163 19.0352 39.2147 21.2727H44V26.7273H39.2147C38.8163 28.9648 37.9364 31.0357 36.686 32.829L40.0706 36.2137L36.2137 40.0706L32.829 36.686C31.0357 37.9364 28.9648 38.8163 26.7273 39.2147V44H21.2727V39.2147C19.0352 38.8163 16.9643 37.9364 15.171 36.686L11.7863 40.0706L7.92939 36.2137L11.314 32.829C10.0636 31.0357 9.18372 28.9648 8.78533 26.7273H4V21.2727H8.78533C9.18372 19.0352 10.0636 16.9643 11.314 15.171L7.92939 11.7863L11.7863 7.92939L15.171 11.314C16.9643 10.0636 19.0352 9.18372 21.2727 8.78533V4H26.7273V8.78533C28.9648 9.18372 31.0357 10.0636 32.829 11.314L36.2137 7.92939L40.0706 11.7863L36.686 15.171Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 29C26.7614 29 29 26.7614 29 24C29 21.2386 26.7614 19 24 19C21.2386 19 19 21.2386 19 24C19 26.7614 21.2386 29 24 29Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceShareThreeSvg = &fyne.StaticResource{
	StaticName: "share-three.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M42 38V42L6 42L6 38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 6L40 16L30 26\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M40 16C20 16 6 19 6 32\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceShareSvg = &fyne.StaticResource{
	StaticName: "share.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M28 6H42V20\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M42 29.4737V39C42 40.6569 40.6569 42 39 42H9C7.34315 42 6 40.6569 6 39V9C6 7.34315 7.34315 6 9 6L18 6\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M25.7998 22.1999L41.0998 6.8999\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSleepSvg = &fyne.StaticResource{
	StaticName: "sleep.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M16.8657 7.46924C16.3036 9.21181 16 11.0705 16 13C16 22.9411 24.0589 31 34 31C36.5346 31 38.9468 30.4762 41.1343 29.5308C38.8006 36.766 32.0116 42 24 42C14.0589 42 6 33.9411 6 24C6 16.5935 10.4734 10.2317 16.8657 7.46924Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M31.6605 10H41L31 18H41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSystemSvg = &fyne.StaticResource{
	StaticName: "system.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M18 6H8C6.89543 6 6 6.89543 6 8V18C6 19.1046 6.89543 20 8 20H18C19.1046 20 20 19.1046 20 18V8C20 6.89543 19.1046 6 18 6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M18 28H8C6.89543 28 6 28.8954 6 30V40C6 41.1046 6.89543 42 8 42H18C19.1046 42 20 41.1046 20 40V30C20 28.8954 19.1046 28 18 28Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M35 20C38.866 20 42 16.866 42 13C42 9.13401 38.866 6 35 6C31.134 6 28 9.13401 28 13C28 16.866 31.134 20 35 20Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M40 28H30C28.8954 28 28 28.8954 28 30V40C28 41.1046 28.8954 42 30 42H40C41.1046 42 42 41.1046 42 40V30C42 28.8954 41.1046 28 40 28Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceTagOneSvg = &fyne.StaticResource{
	StaticName: "tag-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M42.1691 29.2451L29.2631 42.1511C28.5879 42.8271 27.6716 43.2069 26.7161 43.2069C25.7606 43.2069 24.8444 42.8271 24.1691 42.1511L8 26V8H26L42.1691 24.1691C43.5649 25.5732 43.5649 27.841 42.1691 29.2451Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M18.5 21C19.8807 21 21 19.8807 21 18.5C21 17.1193 19.8807 16 18.5 16C17.1193 16 16 17.1193 16 18.5C16 19.8807 17.1193 21 18.5 21Z\" fill=\"#333\"/></svg>"),
}
var resourceTagSvg = &fyne.StaticResource{
	StaticName: "tag.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M8 44L8 6C8 4.89543 8.89543 4 10 4H38C39.1046 4 40 4.89543 40 6V44L24 35.7273L8 44Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M16 18H32\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceTipsSvg = &fyne.StaticResource{
	StaticName: "tips.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M40 20C40 26.8077 35.7484 32.6224 29.7555 34.9336H24H18.2445C12.2516 32.6224 8 26.8077 8 20C8 11.1634 15.1634 4 24 4C32.8366 4 40 11.1634 40 20Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29.7557 34.9336L29.0766 43.0831C29.0334 43.6014 28.6001 44 28.08 44H19.9203C19.4002 44 18.9669 43.6014 18.9238 43.0831L18.2446 34.9336\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 17V23L24 20L30 23V17\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceToolSvg = &fyne.StaticResource{
	StaticName: "tool.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M44 16C44 22.6274 38.6274 28 32 28C29.9733 28 28.0639 27.4975 26.3896 26.6104L9 44L4 39L21.3896 21.6104C20.5025 19.9361 20 18.0267 20 16C20 9.37258 25.3726 4 32 4C34.0267 4 35.9361 4.50245 37.6104 5.38959L30 13L35 18L42.6104 10.3896C43.4975 12.0639 44 13.9733 44 16Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceTranslateSvg = &fyne.StaticResource{
	StaticName: "translate.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M28.2857 37H39.7143M42 42L39.7143 37L42 42ZM26 42L28.2857 37L26 42ZM28.2857 37L34 24L39.7143 37H28.2857Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 6L17 9\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 11H28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 16C10 16 11.7895 22.2609 16.2632 25.7391C20.7368 29.2174 28 32 28 32\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 11C24 11 22.2105 19.2174 17.7368 23.7826C13.2632 28.3478 6 32 6 32\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceUnlikeSvg = &fyne.StaticResource{
	StaticName: "unlike.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M44 19C44 12.9249 39.0751 8 33 8C29.2797 8 25.9907 9.8469 24 12.6738C22.0093 9.8469 18.7203 8 15 8C8.92487 8 4 12.9249 4 19C4 30 17 40 24 42.3262C25.1936 41.9295 26.5616 41.3098 28.0099 40.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M34.959 27L41.8375 35.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M41.8375 27L34.959 35.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceWaterfallsHSvg = &fyne.StaticResource{
	StaticName: "waterfalls-h.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 6H6V17H20V6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M42 31H28V42H42V31Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M42 6H28V23H42V6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M20 25H6V42H20V25Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceWaterfallsVSvg = &fyne.StaticResource{
	StaticName: "waterfalls-v.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M23 20L23 6L6 6L6 20L23 20Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M42 42V28L25 28L25 42H42Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M31 6V20H42V6H31Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M6 28L6 42H17V28H6Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceZoomInSvg = &fyne.StaticResource{
	StaticName: "zoom-in.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21 38C30.3888 38 38 30.3888 38 21C38 11.6112 30.3888 4 21 4C11.6112 4 4 11.6112 4 21C4 30.3888 11.6112 38 21 38Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M21 15L21 27\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15.0156 21.0156L27 21\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33.2216 33.2217L41.7069 41.707\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceZoomOutSvg = &fyne.StaticResource{
	StaticName: "zoom-out.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21 38C30.3888 38 38 30.3888 38 21C38 11.6112 30.3888 4 21 4C11.6112 4 4 11.6112 4 21C4 30.3888 11.6112 38 21 38Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M15 21L27 21\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33.2216 33.2217L41.7069 41.707\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
