// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package Baby

import "fyne.io/fyne/v2"

var resourceBabyAppSvg = &fyne.StaticResource{
	StaticName: "baby-app.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M43 26V32C43 33.1046 42.1046 34 41 34H7C5.89543 34 5 33.1046 5 32V12C5 10.8954 5.89543 10 7 10H16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M4 40L44 40\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"30\" cy=\"17\" r=\"9\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\"/><path d=\"M19 18V16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M41 18V16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 8C29.8333 7 28.8 4.8 26 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 8C30.0833 7 30.6 4.8 32 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"33\" cy=\"16\" r=\"2\" fill=\"#333\"/><circle cx=\"27\" cy=\"16\" r=\"2\" fill=\"#333\"/></svg>"),
}
var resourceBabyBottleSvg = &fyne.StaticResource{
	StaticName: "baby-bottle.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M36 20H12V44H36V20Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M26 36H36\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M26 28H36\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M8 20H40\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 14H20.4V7.6C20.4 6.39815 21.6 4 24 4C26.4 4 27.6 6.39815 27.6 7.6V14H36\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBabyCarSeatSvg = &fyne.StaticResource{
	StaticName: "baby-car-seat.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M36 33L42 4C42 4 31.5 6 31.5 10C31.5 12.5 35.5 14 34 15.5C32.5 17 27 18.5 27 22.5C27 25 28.6406 26.8594 27 28.5C25.5 30 24 29.2143 21.5 28.5C18.7 27.7 13 27 11 27.5C9 28 6.99997 29 7 32C7.00001 33.6492 8 35.5 10.5 36C13 36.5 16 34 20 34C24 34 29 37 32 37C35 37 36 33 36 33Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M11 36L8 44H41L35 36\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBabyFeetSvg = &fyne.StaticResource{
	StaticName: "baby-feet.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M15.0001 20.6121C13.5764 26.7616 21.4929 28.327 19.6238 32.6597C17.7546 36.9923 13.5688 36.1258 14.0361 40.4584C14.5035 44.791 20.0419 44.8519 25.0837 42.2415C35.1675 37.0205 37.2708 25.6166 32.7075 20.6122C27.1002 14.4626 16.4237 14.4626 15.0001 20.6121Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\"/><ellipse cx=\"34.5354\" cy=\"13.5354\" rx=\"2\" ry=\"3\" transform=\"rotate(40 34.5354 13.5354)\" fill=\"#333\"/><ellipse cx=\"29.3807\" cy=\"10.6032\" rx=\"2\" ry=\"3\" transform=\"rotate(25 29.3807 10.6032)\" fill=\"#333\"/><ellipse cx=\"23.3805\" cy=\"9.60278\" rx=\"2\" ry=\"3\" transform=\"rotate(6 23.3805 9.60278)\" fill=\"#333\"/><ellipse cx=\"13.9997\" cy=\"8.00029\" rx=\"3\" ry=\"4\" transform=\"rotate(-20 13.9997 8.00029)\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\"/><ellipse cx=\"38.5353\" cy=\"17.5356\" rx=\"2\" ry=\"3\" transform=\"rotate(50 38.5353 17.5356)\" fill=\"#333\"/></svg>"),
}
var resourceBabyMealSvg = &fyne.StaticResource{
	StaticName: "baby-meal.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 6H10C7.23858 6 5 8.23858 5 11V37C5 39.7614 7.23858 42 10 42H30\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 6V23.5238L5 28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 24L31 28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M37 18V42\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M31 13.3333C31 7.11111 35 4 37 4C39 4 43 7.11111 43 13.3333C43 19.5556 31 19.5556 31 13.3333Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\"/></svg>"),
}
var resourceBabyMobileSvg = &fyne.StaticResource{
	StaticName: "baby-mobile.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4.5 18L24 8L44 18\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 18V4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 30V16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"10\" cy=\"36\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\"/><path d=\"M38 30V16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M32 36L38 30L44 36L38 42L32 36Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29 23V18H19V23\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBabyOneSvg = &fyne.StaticResource{
	StaticName: "baby-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"8\" r=\"5\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5 28C5 28 22 7.75 43 28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M19 28V24.2105C19 24.2105 19 19 24 19C29 19 29 24.2105 29 24.2105V28V32C29 32 29 37 24 37C19 37 19 32 19 32V28Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29 32L37 37L31 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 32L11 37L17 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBabyPantsSvg = &fyne.StaticResource{
	StaticName: "baby-pants.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M34 4H14C12 5 9 9 9 19C9 31.5 14 44 17 44C19 44 19 41.5 19 41.5V24C19 19 27 19.5 27 24V35C27 43 34 46 36 44C38 42 34 40 34 37C34 32 38 28 38 15C38 10 35.6667 6 34 4Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M10 12H37\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10.8032 8C10.0707 9.69577 9.46541 11.9812 9.17871 15\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M37.9995 15C37.9995 12.7719 37.5362 10.7424 36.875 9\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBabySlingSvg = &fyne.StaticResource{
	StaticName: "baby-sling.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"10\" r=\"5\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\"/><path d=\"M24 21C14 21 11 6 11 6L6 8L9 24.5C10.1667 25.1667 14.5 27.5 17 31C19.5 34.5 19 38 24.5 38C30 38 30.5 33.5 32 31C33.5 28.5 37.6667 25 39 24.5L42 8L37 6C37 6 34 21 24 21Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M34 29C34 29 41 33 41 42H36C36 36 31 33 31 33\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 29C15 29 8 33 8 42H13C13 36 18 33 18 33\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBabyTasteSvg = &fyne.StaticResource{
	StaticName: "baby-taste.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 44C33.9411 44 42 35.9411 42 26C42 16.0589 33.9411 8 24 8C14.0589 8 6 16.0589 6 26C6 35.9411 14.0589 44 24 44Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 8C23.75 7 22 4 18 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 8C24.0833 7 24.6 4.8 26 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 33C31 33 29 37 24 37C19 37 17 33 17 33\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 33C31 33 32.5 29 30 29C27.5 29 27 36 27 36\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33 21H29\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17 19V23\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 24V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M44 24V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBibSvg = &fyne.StaticResource{
	StaticName: "bib.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M31 14.0001C31 22.0002 17 22.0002 17 14.0001C17 9.00016 22 8.00008 20 5.0001C18 2.0001 8 7.00005 8 16.0001V32C8 40.5 16.5 44 23.5 44C30.5 44.0001 40 41.0001 40 32V16.0002C40 7.00016 29 2.00012 27 5.0001C25 8.00008 31 9.00016 31 14.0001Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M19 32L24 27L29 32L24 37L19 32Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBoosterCarSeatSvg = &fyne.StaticResource{
	StaticName: "booster-car-seat.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M32 15H16C16 18.47 10.2205 22.9032 6.68333 25.2915C5.12368 26.3445 4 27 4 27C4 27 5 30 7.5 35C9.39377 38.7875 11.5745 40.8536 12.5207 41.6329C12.8255 41.8839 13.2107 42 13.6055 42H35.2984C35.7526 42 36.1923 41.8455 36.5149 41.5258C37.3745 40.6737 39.1873 38.6255 41 35C43.5 30 44 27 44 27C44 27 42.7219 26.361 41 25.2915C37.4456 23.0838 32 19.0419 32 15Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M32 15L34 6L42 6.00001\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 15L14 6L6 6.00001\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 27C4 27 6 31 12 31C18 31 31 31 36 31C41 31 44 27 44 27\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7.5 35.0001C5 30.0001 4 27.0001 4 27.0001C4 27.0001 5.12368 26.3446 6.68333 25.2915\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M41 35.0001C43.5 30.0001 44 27.0001 44 27.0001C44 27.0001 42.7219 26.361 41 25.2915\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBoyOneSvg = &fyne.StaticResource{
	StaticName: "boy-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"11\" r=\"7\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27 44H21L8 24H40L27 44Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBoyStrollerSvg = &fyne.StaticResource{
	StaticName: "boy-stroller.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M40 24H12L14.5 34H36L40 24Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 24L8 15H3.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"20\" cy=\"41\" r=\"3\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"31\" cy=\"41\" r=\"3\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M23 8L32 24H40L44 13C41.6667 10 37 4 34 4C30 4 25.6667 6.66667 23 8Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29 5L33 12\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBoyTwoSvg = &fyne.StaticResource{
	StaticName: "boy-two.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"10\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 44V35L36 32L32 19C32 19 28 16 24 16C20 16 16 19 16 19L12 31L17 35V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBoySvg = &fyne.StaticResource{
	StaticName: "boy.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"10\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 36H18L10 16H38L30 36Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27 36V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M21 36V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceBreastPumpSvg = &fyne.StaticResource{
	StaticName: "breast-pump.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M35 25C35 21 29 19 29 19V14H17V19C17 19 11 21 11 25V44H35V25Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20 4L13 10\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M23 14L17 7\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M26 8H35V15L41 20\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceChairOneSvg = &fyne.StaticResource{
	StaticName: "chair-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M29.4545 23H18.5455C15.8182 23 14 21.3333 14 18.8333V12H18V6C18 4.89543 18.8954 4 20 4H28C29.1046 4 30 4.89543 30 6V12H34V18.8333C34 21.3333 32.1818 23 29.4545 23Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20 23L12 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M28 23L36 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 12H38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 12H10\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17 31L31 31\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 38L33 38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceChairSvg = &fyne.StaticResource{
	StaticName: "chair.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20 23L12 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M28 23L36 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 34L32 34\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29.4545 23H18.5455C15.8182 23 14 21.3333 14 18.8333V12H18V6C18 4.89543 18.8954 4 20 4H28C29.1046 4 30 4.89543 30 6V12H34V18.8333C34 21.3333 32.1818 23 29.4545 23Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 12H38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 12H10\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceChildWithPacifierSvg = &fyne.StaticResource{
	StaticName: "child-with-pacifier.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 42C33.3888 42 41 34.3888 41 25C41 15.6112 33.3888 8 24 8C14.6112 8 7 15.6112 7 25C7 34.3888 14.6112 42 24 42Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M33 21L31 22L29 21\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19 21L17 22L15 21\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 38V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 8C23.75 7 22 4 18 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 8C24.0833 7 24.6 4.8 26 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31.9752 40C31.9752 34 31.9752 31 23.9998 31C15.9998 31 16.0244 34 16.0244 40\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5 23V27\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M43 23V27\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceChildrenPyramidSvg = &fyne.StaticResource{
	StaticName: "children-pyramid.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><rect x=\"15\" y=\"17\" width=\"18\" height=\"8\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 25H38V33H10V25Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M5 33H43V41H5V33Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 17V7\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29 7L19 7\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceCribSvg = &fyne.StaticResource{
	StaticName: "crib.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M38 6V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 40H38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 34H38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 12H42\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M35 6L41 6\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M7 6L13 6\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M10 6V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M17 12V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 12V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 12V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceCryingBabySvg = &fyne.StaticResource{
	StaticName: "crying-baby.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 44C33.9411 44 42 35.9411 42 26C42 16.0589 33.9411 8 24 8C14.0589 8 6 16.0589 6 26C6 35.9411 14.0589 44 24 44Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 8C23.75 7 22 4 18 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 8C24.0833 7 24.6 4.8 26 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 35C31 35 29 31 24 31C19 31 17 35 17 35\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M34 20L28 19\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M20 19L14 20\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 20V25\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33 20V25\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 24V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M44 24V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceFamilySvg = &fyne.StaticResource{
	StaticName: "family.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M10 19C10 19 4.85714 21 4 28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M38 19C38 19 43.1429 21 44 28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M18 19C18 19 22.8 20.1667 24 26\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M30 19C30 19 25.2 20.1667 24 26\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M20 34C20 34 15.8 34.75 14 40\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M28 34C28 34 32.2 34.75 34 40\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"24\" cy=\"31\" r=\"5\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"34\" cy=\"14\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"14\" cy=\"14\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceFloatSvg = &fyne.StaticResource{
	StaticName: "float.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 40C35.0457 40 44 32.8366 44 24C44 15.1634 35.0457 8 24 8C12.9543 8 4 15.1634 4 24C4 32.8366 12.9543 40 24 40Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 28C29.5228 28 34 25.3137 34 22C34 18.6863 29.5228 16 24 16C18.4772 16 14 18.6863 14 22C14 25.3137 18.4772 28 24 28Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M24 16V8\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M32 18C32 18 34.625 14 39 14\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M16 18C16 18 14 14 9 14\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 27C18 27 12 29 11 36\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 27C30 27 36.5 29 37 36\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceGirlOneSvg = &fyne.StaticResource{
	StaticName: "girl-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"11\" r=\"7\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27 24H21L8 44H40L27 24Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceGirlTwoSvg = &fyne.StaticResource{
	StaticName: "girl-two.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"10\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M28 44V36H38L27.2308 16H20.7692L10 36H20V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceGirlSvg = &fyne.StaticResource{
	StaticName: "girl.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><circle cx=\"24\" cy=\"10\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27.2308 16H20.7692L10 36H38L27.2308 16Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27 36V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M21 36V44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceHeartBallonSvg = &fyne.StaticResource{
	StaticName: "heart-ballon.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M17.3333 4C13.3333 4 12 7.15642 12 11.05C12 18.1 19.8 24.5091 24 26C28.2 24.5091 36 18.1 36 11.05C36 7.15642 34.3117 4 30.6667 4C28.4345 4 25.1944 7.0771 24 8.88889C22.8056 7.0771 19.5655 4 17.3333 4Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 26C22 27.0909 19 29.5 19 33C19 36.5 29 35.5 29 39C29 42.5 18 44 18 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceHoldingHandsSvg = &fyne.StaticResource{
	StaticName: "holding-hands.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4.46094 12.8403L22.2354 9.06225C22.7543 8.95197 23.2957 9.05231 23.7405 9.3412L31.8394 14.6007C32.2843 14.8896 32.8257 14.9899 33.3445 14.8797L37.425 14.0123C38.5054 13.7827 39.5674 14.4724 39.7971 15.5528L40.4208 18.4873C40.6505 19.5677 39.9608 20.6297 38.8803 20.8594L31.8655 22.3504C31.3466 22.4607 30.8052 22.3604 30.3604 22.0715L22.2615 16.812C21.8166 16.5231 21.2752 16.4227 20.7564 16.533L17.654 17.1924\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M43.5391 33.1592L25.7646 36.9373C25.2457 37.0475 24.7043 36.9472 24.2595 36.6583L16.1606 31.3988C15.7157 31.1099 15.1743 31.0096 14.6555 31.1199L10.575 31.9872C9.49461 32.2168 8.43258 31.5271 8.20292 30.4467L7.57919 27.5123C7.34954 26.4318 8.03923 25.3698 9.11966 25.1401L16.1345 23.6491C16.6534 23.5388 17.1948 23.6391 17.6396 23.928L25.7385 29.1875C26.1834 29.4764 26.7248 29.5768 27.2436 29.4665L30.346 28.8071\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>"),
}
var resourceOnesiesSvg = &fyne.StaticResource{
	StaticName: "onesies.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 21L4 11C5.83333 9.66667 13 5 24 5C35 5 42 9.66667 44 11L41 21H34V37C34 41 31 44 27 44H21C17 44 14 41 14 37V21H7Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M34 34C34 34 25 34 25 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M14 34C14 34 23 34 23 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29.811 5.5C29.9344 5.97943 30 6.48205 30 7C30 10.3137 27.3137 13 24 13C20.6863 13 18 10.3137 18 7C18 6.48205 18.0656 5.97943 18.189 5.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M35.9997 6.98996C32.8112 5.88268 28.7837 5 23.9997 5C19.2157 5 15.1568 5.88268 11.9463 6.98996\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M14 31C14 31 14 35.875 14 37\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M34 31C34 31 34 35.875 34 37\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M21 44C25 44 24 44 27 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourcePacifierSvg = &fyne.StaticResource{
	StaticName: "pacifier.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><g clip-path=\"url(#icon-16c539fbb20b73)\"><path d=\"M30.6561 21.5855L34.7593 17.4823C36.761 18.0169 38.9853 17.499 40.5556 15.9286C42.8988 13.5855 42.8988 9.78647 40.5556 7.44332C38.2125 5.10018 34.4135 5.10018 32.0703 7.44332C30.5 9.0137 29.9821 11.238 30.5166 13.2397L26.4135 17.3428\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M41.263 32.1922L15.8071 6.73633L11.918 10.6254L19.6962 21.9391L16.8678 26.1818L21.464 30.778L25.7066 27.9495L37.3739 36.0813L41.263 32.1922Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M19.3197 21.8847C15.9285 20.8969 12.117 21.74 9.44302 24.4139C5.53778 28.3192 5.53778 34.6508 9.44302 38.556C13.3483 42.4613 19.6799 42.4613 23.5852 38.556C26.2591 35.8821 27.1022 32.0706 26.1144 28.6793\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g><defs><clipPath id=\"icon-16c539fbb20b73\"><rect width=\"48\" height=\"48\" fill=\"#333\"/></clipPath></defs></svg>"),
}
var resourcePaperShipSvg = &fyne.StaticResource{
	StaticName: "paper-ship.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 24L12.5714 42L24 29L4 24Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M44 24L35.4286 42L24 29L44 24Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M13 42L35 42L24 29L13 42Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 26L24 4L36 26\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceParentingBookSvg = &fyne.StaticResource{
	StaticName: "parenting-book.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M38 31V44C38 44 17.375 44 13.625 44C9.875 44 8 42 8 37C8 32 8 4 8 4H20\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"33\" cy=\"17\" r=\"9\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\"/><path d=\"M22 18V16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M44 18V16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33 8C32.8333 7 31.8 4.8 29 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33 8C33.0833 7 33.6 4.8 35 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"36\" cy=\"16\" r=\"2\" fill=\"#333\"/><circle cx=\"30\" cy=\"16\" r=\"2\" fill=\"#333\"/><path d=\"M8 36H38\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourcePartyBalloonSvg = &fyne.StaticResource{
	StaticName: "party-balloon.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M34 16C35 8 31.1274 4 24.1274 4C17.1274 4 13 9 14 16C15 23 21.2548 28 24.1274 28C27 28 33 24 34 16Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M25 28C23 28.9697 20 31.8889 20 35C20 38.1111 30 36.4444 30 39.5556C30 42.6667 19 44 19 44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourcePokeballOneSvg = &fyne.StaticResource{
	StaticName: "pokeball-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 44C35.0457 44 44 35.0457 44 24C44 12.9543 35.0457 4 24 4C12.9543 4 4 12.9543 4 24C4 35.0457 12.9543 44 24 44Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><circle cx=\"24\" cy=\"24\" r=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M30 24H44\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 24H18\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"24\" cy=\"24\" r=\"2\" fill=\"#333\"/></svg>"),
}
var resourcePowderSvg = &fyne.StaticResource{
	StaticName: "powder.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M44 40V20C44 18.3431 42.6569 17 41 17H35.715C34.1737 17 32.8226 18.2428 31.7911 19.388C30.6326 20.6742 28.3769 22 24 22C19.6231 22 17.3674 20.6742 16.2089 19.388C15.1774 18.2428 13.8263 17 12.285 17H7C5.34315 17 4 18.3431 4 20V40C4 41.6569 5.34315 43 7 43H41C42.6569 43 44 41.6569 44 40Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linejoin=\"round\"/><path d=\"M33 17C33 19.7614 28.9706 22 24 22C19.0294 22 15 19.7614 15 17\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><ellipse cx=\"24\" cy=\"10\" rx=\"9\" ry=\"5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M33 17V10\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 17V10\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><ellipse cx=\"27\" cy=\"10\" rx=\"2\" ry=\"1\" fill=\"#333\"/><ellipse cx=\"21\" cy=\"10\" rx=\"2\" ry=\"1\" fill=\"#333\"/></svg>"),
}
var resourcePreschoolSvg = &fyne.StaticResource{
	StaticName: "preschool.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 35H41C42.1046 35 43 34.1046 43 33V9C43 7.89543 42.1046 7 41 7H7C5.89543 7 5 7.89543 5 9V33C5 34.1046 5.89543 35 7 35Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M14 14V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M34 14V28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M24 17V25\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M20 21H28\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M4 41L44 41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceRadioNannySvg = &fyne.StaticResource{
	StaticName: "radio-nanny.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M36 42.0012V21.6875C36 15.3125 31.0909 10 24 10C16.9091 10 12 15.3125 12 21.6875V42.0012C12 43.1058 12.8954 44 14 44H34C35.1046 44 36 43.1058 36 42.0012Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><circle cx=\"24\" cy=\"23\" r=\"4\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M18 34H20\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M26 38H30\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M12 20V4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>"),
}
var resourceRattleOneSvg = &fyne.StaticResource{
	StaticName: "rattle-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><g clip-path=\"url(#icon-18d0bfc5a2719de9)\"><circle cx=\"29.4632\" cy=\"16.9889\" r=\"11\" transform=\"rotate(40 29.4632 16.9889)\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M38.5327 23.2932C38.5327 23.2932 32.8973 23.7862 27.535 19.2867C22.1727 14.7872 21.6797 9.15186 21.6797 9.15186\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M26.8655 27.8629C23.4051 28.8755 21.7981 30.7906 20.1911 32.7057C18.5842 34.6208 18.5093 37.8215 16.5809 40.1196C14.6526 42.4178 11.8349 42.6643 9.53676 40.7359C7.23863 38.8076 6.99211 35.9899 8.92048 33.6918C10.8488 31.3936 13.9879 30.7641 15.5949 28.849C17.2018 26.9339 18.8088 25.0188 19.2051 21.4351\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M38.832 10.4903C39.897 9.22108 39.7314 7.32882 38.4622 6.26381C37.193 5.19881 35.3007 5.36436 34.2357 6.63358\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g><defs><clipPath id=\"icon-18d0bfc5a2719de9\"><rect width=\"48\" height=\"48\" fill=\"#333\"/></clipPath></defs></svg>"),
}
var resourceRattleSvg = &fyne.StaticResource{
	StaticName: "rattle.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><g clip-path=\"url(#icon-38fde22c3ffed8b0)\"><circle cx=\"30.0746\" cy=\"15.562\" r=\"11\" transform=\"rotate(40 30.0746 15.562)\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M21.6485 8.49117C17.0389 8.53954 15.322 5.1407 13.0722 7.82186C11.0395 10.2443 13.5652 13.4572 11.6369 15.7553\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M25.3022 25.9167C25.3022 25.9167 21.1241 30.8959 19.5171 32.8111C17.9101 34.7262 17.8352 37.9269 15.9069 40.225C13.9785 42.5231 11.1609 42.7696 8.86272 40.8413C6.56459 38.9129 6.31808 36.0952 8.24644 33.7971C10.1748 31.499 13.3139 30.8694 14.9208 28.9543C16.5278 27.0392 20.0837 23.0608 20.7059 22.0599\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"11.2399\" cy=\"19.3392\" r=\"3\" transform=\"rotate(40 11.2399 19.3392)\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"28.4625\" cy=\"37.7069\" r=\"3\" transform=\"rotate(40 28.4625 37.7069)\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M37.2158 24.165C37.8454 27.304 40.0686 32.4331 38.0786 34.0268C36.0886 35.6205 31.554 32.4682 30.3917 35.4091\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g><defs><clipPath id=\"icon-38fde22c3ffed8b0\"><rect width=\"48\" height=\"48\" fill=\"#333\"/></clipPath></defs></svg>"),
}
var resourceRockingHorseSvg = &fyne.StaticResource{
	StaticName: "rocking-horse.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M14 29C14 29 11 24 11 18H27C27 18 27 13.5 30 10C33 6.5 36 5 36 5L44 13.5V18.5L36 16C32 21 34 29 34 29H14Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 29L35 41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 29L13 41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M4 37C4 37 10 43 24 43C38 43 44 37 44 37\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M11 18C11 15 9 12 4 12\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceRomperSvg = &fyne.StaticResource{
	StaticName: "romper.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M6.57241 19.5747L4.40745 12.3582C4.16338 11.5446 4.4545 10.6619 5.17189 10.2071C8.05736 8.37793 14.6413 5 24 5C33.3427 5 39.7999 8.36639 42.7589 10.1977C43.5067 10.6605 43.8274 11.5754 43.5747 12.4177L41.4276 19.5747C41.1738 20.4207 40.3952 21 39.5119 21H36C34.8954 21 34 21.8911 34 22.9957V33.0019C34 34.1065 33.0949 35.0132 32.0273 35.2966C30.7283 35.6415 29.0752 36.3873 28 38C26 41 26 44 26 44H22C22 44 22 41 20 38C18.9248 36.3873 17.2717 35.6415 15.9727 35.2966C14.9051 35.0132 14 34.1065 14 33.0019V22.9957C14 21.8911 13.1046 21 12 21H8.48806C7.60484 21 6.8262 20.4207 6.57241 19.5747Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29.811 5.5C29.9344 5.97943 30 6.48205 30 7C30 10.3137 27.3137 13 24 13C20.6863 13 18 10.3137 18 7C18 6.48205 18.0656 5.97943 18.189 5.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M13.5 6.49375C16.4326 5.63028 19.9575 5 24 5C28.0425 5 31.5449 5.63028 34.4573 6.49375\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSippyCupSvg = &fyne.StaticResource{
	StaticName: "sippy-cup.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M34 44L37 16H11L14.5 44H34Z\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 10L22 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M6 16H42\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M36.9947 25C36.9947 25 42.4654 25 41.968 29.4045C41.4707 33.809 36 32.9281 36 32.9281\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M11.0053 25C11.0053 25 5.53463 25 6.03196 29.4045C6.5293 33.809 12 32.9281 12 32.9281\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M37 10H11V16H37V10Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSleepOneSvg = &fyne.StaticResource{
	StaticName: "sleep-one.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 6H24.1429L7 24H25\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M29 15H41L29 29H41\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M15 32H24.0476L15 42H25\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceSteollerSvg = &fyne.StaticResource{
	StaticName: "steoller.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M40 24H12L14.5 34H36L40 24Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M12 24L8 15H3.5\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"20\" cy=\"41\" r=\"3\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><circle cx=\"31\" cy=\"41\" r=\"3\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M23 8.0002L28 24.0002H40C40 24.0002 43.5 16.0002 37.5 10.0002C31.5 4.00022 25.6667 6.66686 23 8.0002Z\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
var resourceTireSwingSvg = &fyne.StaticResource{
	StaticName: "tire-swing.svg",
	StaticContent: []byte(
		"<svg width=\"48\" height=\"48\" viewBox=\"0 0 48 48\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 4C4 4 10 10 24 10C38 10 44 4 44 4\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M24 10V16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><ellipse cx=\"30\" cy=\"30\" rx=\"8\" ry=\"14\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><ellipse cx=\"30\" cy=\"30\" rx=\"3\" ry=\"6\" fill=\"none\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M18 44C13.5817 44 10 37.732 10 30C10 22.268 13.5817 16 18 16\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 16H18\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M30 44H18\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M22 29H10\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M23 22L12 22\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M23 37H12\" stroke=\"#333\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"),
}
